name 'continuent-oracle'
version '0.0.2'
source 'git://github.com/continuent/continuent-oracle.git'
author 'Continuent'
license 'Apache 2.0'
summary 'Oracle module'
description 'Oracle module'
project_page 'https://github.com/continuent/continuent-oracle'
dependency 'puppetlabs/stdlib', '>= 3.2.0'
dependency 'fiddyspence/sysctl', '>= 0.3.1'
